# Generated by Django 4.1.7 on 2023-05-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
    ]
